/* Autogenerated by png2wx.pl on Wed Mar 30 16:00:20 2011 */
#ifndef ICONS_H
#define ICONS_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *_img_wmm;
extern wxBitmap *_img_wmm_pi;

#endif /* ICONS_H */
